/****************************************************************************
 *
 *   Copyright (C) 2013-2015 PX4 Development Team. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 * 3. Neither the name PX4 nor the names of its contributors may be
 *    used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 ****************************************************************************/

/* Auto-generated by genmsg_cpp from file /Users/Siddharth/Documents/Programming/3dr/ardupilot-temp/libraries/AP_GST/msg/esc_status.msg */


#pragma once

#include <stdint.h>
#include <AP_GST/AP_GST_Helper.h>

#include <uORB/topics/esc_report.h>

/**
 * @addtogroup topics
 * @{
 */


struct esc_status_s {
	uint16_t counter;
	uint64_t timestamp;
	uint8_t esc_count;
	uint8_t esc_connectiontype;
	struct esc_report_s esc[8];
	static const uint8_t CONNECTED_ESC_MAX = 8;
	static const uint8_t ESC_VENDOR_GENERIC = 0;
	static const uint8_t ESC_VENDOR_MIKROKOPTER = 1;
	static const uint8_t ESC_VENDOR_GRAUPNER_HOTT = 2;
	static const uint8_t ESC_CONNECTION_TYPE_PPM = 0;
	static const uint8_t ESC_CONNECTION_TYPE_SERIAL = 1;
	static const uint8_t ESC_CONNECTION_TYPE_ONESHOOT = 2;
	static const uint8_t ESC_CONNECTION_TYPE_I2C = 3;
	static const uint8_t ESC_CONNECTION_TYPE_CAN = 4;

};

/**
 * @}
 */

/* register this as object request broker structure */
GST_DECLARE(esc_status);
